export const ADMIN_DELETE_PRODUCT_REQUEST="ADMIN_DELETE_PRODUCT_REQUEST";
export const ADMIN_DELETE_PRODUCT_SUCCESS="ADMIN_DELETE_PRODUCT_SUCCESS";
export const ADMIN_DELETE_PRODUCT_FAIL="ADMIN_DELETE_PRODUCT_FAIL";






