version: "3"
services:
  shopping-backend:
    build: ./shopping-backend
    ports:
      - "5000:5000"
    container_name: shopping-backend
  shopping-frontend:
    build: ./shopping-frontend
    ports:
      - "80:3000"
    container_name: shopping-frontend
