export const GET_ORDER_REQUEST="GET_ORDER_REQUEST";
export const GET_ORDER_SUCCESS="GET_ORDER_SUCCESS";
export const GET_ORDER_FAIL='GET_ORDER_FAIL';

export const ORDER_PAYPAL_REQUEST="ORDER_PAYPAL_REQUEST";
export const ORDER_PAYPAL_SUCCESS="ORDER_PAYPAL_SUCCESS";
export const ORDER_PAYPAL_FAIL=" ORDER_PAYPAL_FAIL";

export const ORDER_RESET="ORDER_RESET"
export const DELIVER_RESET="DELIVER_RESET";

export const ORDER_DELIVER_REQUEST="ORDER_DELIVER_REQUEST";
export const ORDER_DELIVER_SUCCESS="ORDER_DELIVER_SUCCESS";
export const ORDER_DELIVER_FAIL="ORDER_DELIVER_FAIL";


