export const ADMIN_ALL_USERS="ADMIN_ALL_USERS";
export const ADMIN_USERS_SUCCESS="ADMIN_USERS_SUCCESS";
export const ADMIN_USERS_FAIL="ADMIN_USERS_FAIL";

export const DELETE_USER="DELETE_USER";
export const DELETE_FAIL="DELETE_FAIL";
export const DELETE_REQUEST="DELETE_REQUEST";

export const ADMIN_USER_DETAIL="ADMIN_USER_DETAIL";
export const ADMIN_USER_SUCCESS="ADMIN_USER_SUCCESS";
export const ADMIN_USER_FAIL="ADMIN_USER_FAIL";

export const ADMIN_USER_UPDATE="ADMIN_USER_UPDATE";
export const ADMIN_USER_UPDATE_SUCCESS="ADMIN_USER_UPDATE_SUCCESS";
export const ADMIN_USER_UPDATE_FAIL="ADMIN_USER_UPDATE_FAIL";

export const ADMIN_USER_RESET="ADMIN_USER_RESET"
