export const GET_PRODUCTS_REQUEST="GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS="GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAIL="GET_PRODUCTS_FAIL";

export const ADMIN_CREATE_PRODUCT_REQUEST="ADMIN_CREATE_PRODUCT_REQUEST";
export const ADMIN_CREATE_PRODUCT_SUCCESS="ADMIN_CREATE_PRODUCT_SUCCESS";
export const ADMIN_CREATE_PRODUCT_FAIL="ADMIN_CREATE_PRODUCT_FAIL";

export const CREATE_RESET="CREATE_RESET"

export const GET_TOP_PRODUCTS_REQUEST="GET_TOP_PRODUCTS";
export const GET_TOP_PRODUCTS_SUCCESS="GET_TOP_PRODUCTS_SUCCESS";
export const GET_TOP_PRODUCTS_FAIL="GET_TOP_PRODUCTS_FAIL"
