export const GET_PRODUCT_REQUEST="GET_PRODUCT_REQUEST";
export const GET_PRODUCT_SUCCESS="GET_PRODUCT_SUCCESS";
export const GET_PRODUCT_FAIL="GET_PRODUCT_FAIL"

export const ADMIN_UPDATE_PRODUCT_REQUEST="ADMIN_UPDATE_PRODUCT_REQUEST";
export const ADMIN_UPDATE_PRODUCT_SUCCESS="ADMIN_UPDATE_PRODUCT_SUCCESS";
export const ADMIN_UPDATE_PRODUCT_FAIL="ADMIN_UPDATE_PRODUCT_FAIL";
export const ADMIN_PRODUCT_RESET="ADMIN_PRODUCT_RESET";

export const ADD_REVIEWS_REQUEST="ADD_REVIEWS_REQUEST";
export const ADD_REVIEWS_SUCCESS="ADD_REVIEWS_SUCCESS";
export const ADD_REVIEWS_FAIL="ADD_REVIEWS_FAIL";


