export const LOGIN_REQUEST="LOGIN_REQUEST";
export const LOGIN_SUCCESS="LOGIN_SUCCESS";
export const LOGIN_FAIL="LOGIN_FAIL";
export const LOG_OUT="LOG_OUT";
export const LOG_RESET="LOG_RESET";
export const REGISTER_REQUEST="REGISTER_REQUEST";
export const REGISTER_SUCCESS="REGISTER_SUCCESS";
export const REGISTER_FAIL="REGISTER_FAIL";
export const REGISTER_RESET="REGISTER_RESET";

export const UPDATE_PROFILE_REQUEST="UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS="UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAIL="UPDATE_PROFILE_FAIL";

export const GET_PROFILE_REQUEST="GET_PROFILE_REQUEST";
export const GET_PROFILE_SUCCESS=" GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAIL="GET_PROFILE_FAIL";
export const PROFILE_RESET="PROFILE_RESET";

export const GET_ALL_ORDERS="GET_ALL_ORDERS";
export const GET_ALL_ORDERS_SUCCESS="GET_ALL_ORDERS_SUCCESS";
export const GET_ALL_ORDERS_FAIL="GET_ALL_ORDERS_FAIL";

